#!/usr/bin/env bash

TARGETS="eq ne gt ge lt le"

Build() {
   local target=$1
   echo "CC: $target.c  ->  $target"
   gcc "$target.c" -o "$target"
}

Install() {
   local LOC="/usr/local/bin"
   local i
   for i in $TARGETS
   do
      if [ ! -f "$i" ]
      then
         Build $i
      fi
      echo "Install:  $i  ->  $LOC/$i"
      install "$i" "$LOC/$i"
   done
}

PASS="    PASS"
FAIL="    FAIL"

EQTests() {
   echo "eq ..."
   echo "  test 1 ..."
   if ./eq blah blah blah; then echo "$PASS"; else echo "$FAIL"; fi
   echo "  test 2 ..."
   if ./eq blah blah blah blah blah halb; then echo "$FAIL"; else echo "$PASS"; fi
   echo "  test 3 ..."
   if ./eq 10 10; then echo "$PASS"; else echo "$FAIL"; fi
   echo "  test 4 ..."
   if ./eq 14.3 14.3; then echo "$PASS"; else echo "$FAIL"; fi
}

NETests() {
   echo "ne ..."
   echo "  test 1 ..."
   if ./ne blah blah blah; then echo "$FAIL"; else echo "$PASS"; fi
   echo "  test 2 ..."
   if ./ne blah blah halb blah; then echo "$PASS"; else echo "$FAIL"; fi
   echo "  test 3 ..."
   if ./ne 1 15; then echo "$PASS"; else echo "$FAIL"; fi
   echo "  test 4 ..."
   if ./ne 5.5 9.3; then echo "$PASS"; else echo "$FAIL"; fi
}

GTTests() {
   echo "gt ..."
   echo "  test 1 ..."
   if ./gt 5 4; then echo "$PASS"; else echo "$FAIL";fi
   echo "  test 2 ..."
   if ./gt 6.7 4.2; then echo "$PASS"; else echo "$FAIL";fi
}

GETests() {
   echo "ge ..."
   echo "  test 1 ..."
   if ./ge 10 6; then echo "$PASS"; else echo "$FAIL"; fi
   echo "  test 2 ..."
   if ./ge 7 7; then echo "$PASS"; else echo "$FAIL"; fi
   echo "  test 3 ..."
   if ./ge 1.3 0.4; then echo "$PASS"; else echo "$FAIL"; fi
}

LTTests() {
   echo "lt ..."
   echo "  test 1 ..."
   if ./lt 8 20; then echo "$PASS"; else echo "$FAIL"; fi
   echo "  test 2 ..."
   if ./lt 7.1 80.8; then echo "$PASS"; else echo "$FAIL"; fi
}

LETests() {
   echo "le ..."
   echo "  test 1 ..."
   if ./le 7 18; then echo "$PASS"; else echo "$FAIL"; fi
   echo "  test 2 ..."
   if ./le 8 8; then echo "$PASS"; else echo "$FAIL"; fi
   echo "  test 3 ..."
   if ./le 56.6 78.9; then echo "$PASS"; else echo "$FAIL"; fi
}

RunTests() {
   local i
   local ERR=0
   for i in $TARGETS
   do
      if [ ! -f "$i" ]
      then
         Build $i
         if [ ! -f "$i" ]
         then
           (( ERR++ ))
         fi
      fi
   done
   if (( ERR ))
   then
      echo "All targets did not compile successfully, exiting..."
      return
   fi
   echo "Running tests..."
   EQTests
   NETests
   GTTests
   GETests
   LTTests
   LETests
}

if [ "$1" = "" ]
then
   for i in $TARGETS
   do
      Build $i
   done
else
   if [ "$1" = "install" ]
   then
      Install
      exit
   fi
   if [ "$1" = "clean" ]
   then
      rm -f $TARGETS
      exit
   fi
   if [ "$1" = "help" ]
   then
      echo "usage: $0 [install|clean]"
      exit
   fi
   if [ "$1" = "test" ]
   then
      RunTests
      exit
   fi
   for i in "$@"
   do
      Build "$i"
   done
fi
