# .bash_aliases
# Fedora

alias ..='cd ../'
alias ls='ls -F --color=auto'
alias la='ls -A --color=auto'
alias ll='ls -Al --color=auto'
alias attach='screen -raAd'
alias yum='sudo yum'
alias rec-desk='record_desktop $1'
