#
# ~/.bash_aliases
# (ArchLinux)
#

alias ls='ls -F --color=auto'
alias la='ls -A'
alias ll='ls -Al'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias attach='screen -raAd'
alias pacman='sudo pacman'
alias yt='youtube-dl -l'

# cower
alias cower='cower --color=auto'
alias aursc='cower -s'
alias aurdl='cower -d'
alias aurin='cower_aur_install $@'
