#!/usr/bin/env python

import os
import sys

def cdirs(dirname, newdirname):
  try:
    os.makedirs(os.path.join(dirname, newdirname))
  except:
    print "An error occurred"
    sys.exit(1)

def mk_readme(auth, name):
  try:
    f = open(os.path.join(os.getcwd(), "README"), "w")
    try:
      f.write(
         "Author: " + auth + os.linesep + "App name: " + name + os.linesep
      )
    except (IOError, OSError), e:
      print str(e)
      sys.exit(2)
  finally:
    f.close()

def main():
  if len(sys.argv) != 3:
    print "Incorrect number of args"
    print "Usage: %s [APPNAME] [AUTHOR]" % sys.argv[0]
    sys.exit(1)

  name = sys.argv[1]
  dir = os.getcwd()
  auth = sys.argv[2]

  cdirs(dir, name)
  os.chdir(os.path.join(dir, name))
  os.system("touch AndroidManifest.xml build.xml Android.mk")
  cdirs(os.getcwd(), "src/com/%s/%s" % (auth.lower(), name.lower()))
  os.system("touch src/com/%s/%s/%s.java" % (auth.lower(), name.lower(), name))
  os.system("mkdir -p res/{layout,drawable-hdpi,values}")
  os.system("touch res/layout/main.xml res/values/strings.xml")
  mk_readme(auth, name)
  sys.exit(0)

if __name__ == '__main__':
  main()
