#!/bin/sh
#
# Automatically downloads latest CyanogenMod nightly builds for any CM-supported device
# nathanForbes
#

URL="http://mirror.kanged.net/cm/nightly"

DIR="$HOME/nightly.p"
INDEX="${DIR}/index.html"
TEMP="${DIR}/nightly-index.tmp"

DATE=`date +%m%d%Y`   					# today
TOMORROW=$((`date +%d`+1))				# add 1 to the day of month integer
TOMORROW_DATE="`date +%m`${TOMORROW}`date +%Y`"		# insert the $TOMORROW var into full date

READER_FRIENDLY_DATE=`date +%m/%d/%Y`
READER_FRIENDLY_TOMORROW_DATE="`date +%m`/${TOMORROW}/`date +%Y`"

today()
{
	TODAY_INDEXED=`cat ${TEMP} | grep "cm_${1}-${DATE}" | awk '{print $1}'`

	if [ ! -f "$HOME/nightlies/${TODAY_INDEXED}" ]
	then
		echo "CyanogenMod nightly for ${1}-${READER_FRIENDLY_DATE} found!"
		echo -n "Proceed with download now? (y/n): "
		read PROCEED2
		case "${PROCEED2}" in
			y|Y|yes|YES)
				echo "Attempting download, please wait..."
				cd $HOME/nightlies
				wget ${URL}/${1}/${TODAY_INDEXED}
				if [ "$?" -ne 0 ]
				then
					echo "Download failed!"
					rm -rf ${TODAY_INDEXED} ${DIR}; exit 1
				else
					echo "New ${1}-${READER_FRIENDLY_DATE} nightly located at:"
					echo "	$HOME/nightlies/${TODAY_INDEXED}"
				fi
				;;
			n|no|N|NO)
				echo "Not downloading ${1}-${READER_FRIENDLY_DATE} nightly at this time..."
				;;
			*)
				echo "'${PROCEED2}' not recognized...try again"
				rm -rf ${DIR}; exit 1
				;;
		esac
	else
		echo "${1}-${TODAY_INDEXED} already exists in /sdcard!"
		rm -rf ${DIR}; exit 1
	fi
	return
}

tomorrow()
{
	TOMORROW_INDEXED=`cat ${TEMP} | grep "cm_${1}-${TOMORROW_DATE}" | awk '{print $1}'`

	if [ ! -f "$HOME/nightlies/${TOMORROW_INDEXED}" ]
	then
		echo "New CyanogenMod nightly for ${1}-${READER_FRIENDLY_TOMORROW_DATE} found!"
		echo -n "Proceed with download now? (y/n): "
		read PROCEED
		case "${PROCEED}" in
			y|Y|yes|YES)
				echo "Attempting download, please wait..."
				cd $HOME/nightlies
				wget ${URL}/${1}/${TOMORROW_INDEXED}
				if [ "$?" -ne 0 ]
				then
					echo "Download failed!"
					rm -rf ${TOMORROW_INDEXED} ${DIR}; exit 1
				else
					echo "New ${1}-${READER_FRIENDLY_TOMORROW_DATE} nightly located at:"
					echo "	$HOME/nightlies/${TOMORROW_INDEXED}"
				fi
				;;
			n|N|no|NO)
				echo "Not downloading ${1}-${READER_FRIENDLY_TOMORROW_DATE} nightly at this time..."
				;;
			*)
				echo "'${PROCEED}' not recognized, try again..."
				rm -rf ${DIR}; exit 1
				;;
		esac
	else
		echo "${1}-${TOMORROW_INDEXED} already exists in /sdcard!"
		rm -rf ${DIR}; exit 1
	fi
	return
}

parse_nightly()
{
	echo "Working, please wait..."

	mkdir -p ${DIR}; cd ${DIR};
	rm -rf ${INDEX} ${TEMP}
	wget -q ${URL}/${1}/

	if [ "$?" -eq 0 ]
	then
		if [ -e "${INDEX}" ]
		then
			awk -F'[<>]' '{for(x=1;x<=NF;x++) if($x ~ /.zip$/) print $x}' ${INDEX} >${TEMP}

			if [ -e "${TEMP}" ]; then rm -rf ${INDEX}; fi;
		else
			echo "Error parsing!"
			cd ..; rm -rf ${DIR}; exit 1
		fi
	else
		echo "Error parsing!"
		cd ..; rm -rf ${DIR}; exit 1
	fi

	if [ "`cat ${TEMP} | grep "cm_${1}-${TOMORROW_DATE}" | awk '{print $1}'`" != "" ]
	then
		tomorrow ${1}
	else
		if [ "`cat ${TEMP} | grep "cm_${1}-${DATE}" | awk '{print $1}'`" != "" ]
		then
			echo "No nightly found for ${1}-${READER_FRIENDLY_TOMORROW_DATE}, (tomorrow)..."
			echo -n "Try today's date instead? (y/n): "
			read TODAY
			case "${TODAY}" in
				y|Y|yes|YES)
					today ${1}
					;;
				n|N|no|NO)
					echo "Not checking for new nightly for today on ${READER_FRIENDLY_DATE}"
					;;
				*)
					echo "'${TODAY}' not recognized, try again..."
					rm -rf ${DIR}; exit 1
					;;
			esac
		else
			echo "No ${1}-${READER_FRIENDLY_DATE} found. Please wait for a newer nightly"
		fi
	fi
	return
}


echo -n "Your device: "

read DEVICE

case "${DEVICE}" in

	bravo|expresso|hero|heroc|inc|liberty|passion|sholes|supersonic) parse_nightly ${DEVICE}
					;;
			dream|sapphire) parse_nightly dream_sapphire
					;;
	     			     *) echo "${DEVICE} not currently supported"
					;;

esac

rm -rf ${DIR}

exit 0
