#!/bin/bash
#
# Uncomments "#force_color_prompt=yes" in ~/.bashrc
# Ubuntu Lucid Lynx is the only distro this has been tested on
# natediddy
#

A="#force_color_prompt=yes"
B="force_color_prompt=yes"
C=$HOME/.bashrc


color_on()
{
	if grep "$A" "$C" >/dev/null
	then
		sed -i -e "s/$A/$B/" $C
		if grep "$B" "$C" >/dev/null
		then
			echo "Color: ON"
            echo "Run 'source ~/.bashrc' to take affect"
		else
			echo "Fail"
		fi
    else
        echo "Color already on"
	fi
}

color_off()
{
	if grep "$B" "$C" >/dev/null
	then
		sed -i -e "s/$B/$A/" $C
		if grep "$A" "$C" >/dev/null
		then
			echo "Color: OFF"
            echo "Run 'source ~/.bashrc' to take affect"
		else
			echo "Fail"
		fi
    else
        echo "Color already off"
	fi
}

case "$1" in
	color-on)
		color_on ;;
	color-off)
		color_off ;;
	*)
		echo "usage: $0 [ color-on | color-off ]" ;;
esac
