#!/bin/bash
#
# Quick Android app template
# natediddy
#

# XXX: EDITME
PKG_PREFIX=com.nathanforbes

# EXAMPLE:
#PKG_PREFIX=com.nathan

if [ ! $1 ]
then
	echo "App name not provided"
	exit 1
fi

$( which android ) create project \
	--name $1 \
	--target 4 \
	--path $( pwd )/$1 \
	--package $( echo "$PKG_PREFIX" ).$( echo "$1" | tr [:upper:] [:lower:] ) \
	--activity $1

exit
