#!/bin/sh
#
# VERY simple (but handy) Irssi notification script
# XXX: Only for use with Irssi Script: "fnotify.pl"
#
# Intended to be ran with 'screen' in it's own 'screen',
# (as it just loops forever)
#
# nathanForbes
#

if [ ! -e "$HOME/.irssi/scripts/fnotify.pl" ]
then
    if [ ! -e "$HOME/.irssi/scripts/autorun/fnotify.pl" ]
    then
cat <<EOF

"fnotify.pl" script not found!
Place script in either "~/.irssi/scripts" or
"~/.irssi/scripts/autorun" and load from irssi

Copy/paste the contents of the script into a file named "fnotify.pl" from here:
        http://www.leemhuis.info/files/fnotify/fnotify

EOF
        exit 1
    fi
fi

x="$HOME/.irssi/fnotify"

# Infinite loop - prints nothing if no new privmsgs, hilights, etc.
while true
do
    if [ -e "$x" ]
    then
        echo
        echo "`date +%b` `date +%d` `date +%I`:`date +%M%p`"
        sed = $x | sed 'N;s/\n/\) => ! => /' | sed G 
        ( cat $x >> $x.log.all )
        rm -rf $x
    fi
    sleep 5m 
done
