#!/bin/bash
#
# *DO NOT* use this on a public or shared computer!
# You must edit MY_PASS to contain your sudo login password
#
# This is useful for keeping your installed packages up-to-date
# without needing to manually run apt-get update & upgrade
#
# Using sudo's -S option allows us to read the password from
# standard input, eliminating the sudo password prompt.
# And in conjuction with apt-get's -y option you will not be
# prompted to verify upgrading packages (apt-get assumes yes to all)
#
# - {n8}
#

MY_PASS="YOUR_SUDO_PASSWORD" # EDITME

echo "$MY_PASS" | sudo -S apt-get update -y
echo "$MY_PASS" | sudo -S apt-get upgrade -y
